# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_templates": "01_extract_dtsek_from_image.ipynb",
         "mtm": "01_extract_dtsek_from_image.ipynb",
         "get_ocr_output": "01_extract_dtsek_from_image.ipynb",
         "get_symbol": "01_extract_dtsek_from_image.ipynb",
         "get_full_text_annotations": "01_extract_dtsek_from_image.ipynb",
         "resize_boxes": "01_extract_dtsek_from_image.ipynb",
         "cls_box_into_line": "01_extract_dtsek_from_image.ipynb",
         "find_double_tsek_bf": "01_extract_dtsek_from_image.ipynb",
         "compute_iou": "01_extract_dtsek_from_image.ipynb",
         "get_double_tsek_idx": "01_extract_dtsek_from_image.ipynb",
         "put_whitespaces": "01_extract_dtsek_from_image.ipynb",
         "rm_running_head": "01_extract_dtsek_from_image.ipynb",
         "rm_noise": "01_extract_dtsek_from_image.ipynb",
         "postprocess": "01_extract_dtsek_from_image.ipynb",
         "str_insert": "01_extract_dtsek_from_image.ipynb",
         "add_double_tsek": "01_extract_dtsek_from_image.ipynb",
         "extract_double_tsek_vol": "01_extract_dtsek_from_image.ipynb",
         "get_double_tsek_vol_by_pages": "01_extract_dtsek_from_image.ipynb",
         "main": "01_extract_dtsek_from_image.ipynb",
         "get_index_layer": "02_transerfer_dtsek_to_dergey.ipynb",
         "get_base_text": "02_transerfer_dtsek_to_dergey.ipynb",
         "isNSM": "02_transerfer_dtsek_to_dergey.ipynb",
         "get_first_char_idx": "02_transerfer_dtsek_to_dergey.ipynb",
         "parse_double_tsek": "02_transerfer_dtsek_to_dergey.ipynb",
         "adjust_next_diff": "02_transerfer_dtsek_to_dergey.ipynb",
         "transfer_anns_with_diff": "02_transerfer_dtsek_to_dergey.ipynb"}

modules = ["extract_dtsek_from_image.py",
           "transfer_dtsek_to_dergey.py"]

doc_url = "https://10zinten.github.io/dtsek//dtsek/"

git_url = "https://github.com/10zinten/dtsek/tree/master/"

def custom_doc_links(name): return None
